disabled_rules:
  - identifier_name
  - type_name
  - cyclomatic_complexity
  - function_body_length
opt_in_rules:
  - sorted_imports

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

todo:
  only: FIXME
